# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'temperature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\x12\x0btemperature\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n\x12TemperatureRequest\x12\r\n\x05value\x18\x01 \x01(\x01\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"S\n\x13TemperatureResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x0f\n\rStreamRequest2\xb5\x01\n\x12TemperatureService\x12J\n\x0fPushTemperature\x12\x1f.temperature.TemperatureRequest\x1a\x16.google.protobuf.Empty\x12S\n\x11StreamTemperature\x12\x1a.temperature.StreamRequest\x1a .temperature.TemperatureResponse0\x01\x42\x0fZ\r.;temperatureb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r.;temperature'
  _globals['_TEMPERATUREREQUEST']._serialized_start=96
  _globals['_TEMPERATUREREQUEST']._serialized_end=178
  _globals['_TEMPERATURERESPONSE']._serialized_start=180
  _globals['_TEMPERATURERESPONSE']._serialized_end=263
  _globals['_STREAMREQUEST']._serialized_start=265
  _globals['_STREAMREQUEST']._serialized_end=280
  _globals['_TEMPERATURESERVICE']._serialized_start=283
  _globals['_TEMPERATURESERVICE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
